Update ReadtheDocs links to new documentation sites
ROCmSoftwarePlatform/hipSOLVER pull request #216
Opened 2023-12-22 18:11 UTC by samjwu

Replaces ReadtheDocs for Community links (.io) (being retired) with for Business (.com)

Also applies some automatic Markdown formatting changes to the changelog

2024-01-05 20:16 UTC, tfalders requested changes
Looks good, though I have concerns about the changes to the changelog.

2024-01-05 20:16 UTC, tfalders commented on CHANGELOG.md
I'm not a fan of the changelog changes. It makes it much harder to isolate specific releases when viewing the raw file. Is there a specific rationale for the changes or can we revert?

2024-01-05 20:53 UTC, samjwu commented on CHANGELOG.md
It was mainly to address markdown linting violations (eg: they require a newline between each header and paragraph), but this can also be reverted.

2024-01-08 17:51 UTC, samjwu commented on CHANGELOG.md
Reverted in latest. Only the doc link was updated.

2024-01-08 20:40 UTC, tfalders approved these changes

2024-01-08 21:31 UTC, merged